services:
  - type: web
    name: wainkom-backend
    env: node
    plan: free
    buildCommand: npm install && tsc
    startCommand: node dist/app.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: true
